-- TRUNCATE  "VeteranWar" CASCADE;
-- TRUNCATE  "VeteranBranch" CASCADE;
-- TRUNCATE  "Veterans" CASCADE;;
-- TRUNCATE  "Kins" CASCADE;
-- TRUNCATE  "Burials" CASCADE;
-- TRUNCATE  "VeteranRank" CASCADE;
-- TRUNCATE  "Ranks" CASCADE;
-- TRUNCATE  "Branches" CASCADE;
 TRUNCATE  "Cemeteries" ;
-- TRUNCATE  "Wars" CASCADE;
